shop/acl/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import include, url
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from django.contrib import auth
from django.shortcuts import HttpResponseRedirect
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required

from django.views.generic.base import TemplateView
from django.views.generic import RedirectView

from django.shortcuts import render_to_response, render

from .views import *



app_name = 'acl'
urlpatterns = [
	url(r'^acl/perm/list/?$', login_required(acl_perm_list.as_view()), name='acl_perm_list'),
	#aclu
	url(r'^acl/aclu/edit/(?P<pk>\d+)/?$', login_required(acl_aclu_edit.as_view()), name='acl_aclu_edit'),
	url(r'^acl/aclu/add/(?P<pk>\d+)/?$', login_required(acl_aclu_add.as_view()), name='acl_aclu_add'),
	url(r'^acl/aclu/del/(?P<pk>\d+)/?$', login_required(acl_aclu_del.as_view()), name='acl_aclu_del'),
	#aclg
	url(r'^acl/aclg/edit/(?P<pk>\d+)/?$', login_required(acl_aclg_edit.as_view()), name='acl_aclg_edit'),
	url(r'^acl/aclg/add/(?P<pk>\d+)/?$', login_required(acl_aclg_add.as_view()), name='acl_aclg_add'),
	url(r'^acl/aclg/del/(?P<pk>\d+)/?$', login_required(acl_aclg_del.as_view()), name='acl_aclg_del'),
	
]

shop/dj/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include, url

from django.conf import settings
from django.conf.urls.static import static

from django.contrib import auth
from django.shortcuts import HttpResponseRedirect
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required

from django.views.generic.base import TemplateView
from django.views.generic import RedirectView

from django.shortcuts import render_to_response, render

from .views import *

def auth_logout(request):
	auth.logout(request)
	return HttpResponseRedirect("/user/login")
	
	
def getcap(request):
	from django.http import HttpResponse
	import json
	from captcha.models import CaptchaStore
	from captcha.helpers import captcha_image_url
	newcapkey = CaptchaStore.generate_key()
	newcapimg  = captcha_image_url(newcapkey)
	tmp={'res': 1, 'key': newcapkey, 'img': newcapimg,}
	return HttpResponse(json.dumps(tmp), content_type='application/json')
	

class test(TemplateView):
	template_name = 'test.html'
	
class test2(TemplateView):
	template_name = 'test2.html'
	
def my404(request):
	return render(request, '404.html', status=404)
	
def my500(request):
	return render(request, '500.html', status=500)

handler404 = my404
handler500 = my500
	
	

urlpatterns = [
	#include app urls
	url(r'^', include('acl.urls')),
	url(r'^', include('shopapp.urls')),
	url(r'^', include('banerapp.urls')),
	#url(r'^', include('newsapp.urls')),
	#url(r'^', include('panel.urls')),
	#
	url(r'^test/?$', test.as_view()),
	url(r'^test2/?$', test2.as_view()),
	#
	url(r'^user/logout/?$', auth_logout),
	url(r'^getcap/?$', getcap),
	#
	url(r'^captcha/', include('captcha.urls')),
	path('admin/', admin.site.urls),
	#url(r'^i18n/', include('django.conf.urls.i18n')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.site_title = 'shop'
admin.site.site_header = 'shop'


# if settings.DEBUG:
	# import debug_toolbar
	# urlpatterns += [
		# url(r'^__debug__/', include(debug_toolbar.urls)),
	# ]

shop/acl/models.py
# -*- coding: utf-8 -*-
from django.db import models

from PIL import Image
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill, ResizeToFit, SmartResize, Transpose, Adjust

from django.db.models.signals import post_delete, post_save
from django.db.models.signals import pre_delete

from django.contrib.auth.models import User, Group, UserManager

from django.core.validators import MinValueValidator, MaxValueValidator

import datetime
from django.utils import timezone

from node.models import *
from panel.models import *


class aclobject(models.Model):
	id = models.AutoField(primary_key=True, unique=True, verbose_name='id')
	name = models.CharField(verbose_name=u'Название', max_length=200)
	objectid = models.CharField(verbose_name=u'ID объекта', max_length=200)
	
	def __str__(self):
		return u'%s %s %s' % (self.id, self.name, self.objectid)

	class Meta:
		ordering=['-id']
		verbose_name = u'aclobject'
		verbose_name_plural = u'aclobject'


grantchoice=(('A', 'All'), ('L', 'Список'), ('R', 'Чтение'), ('C', 'Создание'), ('U', 'Редактирование'),)

class aclu(models.Model):
	id = models.AutoField(primary_key=True, unique=True, verbose_name='id')
	#name = models.CharField(verbose_name=u'Название', max_length=200)
	status = models.BooleanField(verbose_name='Статус', default=True)
	#
	aclobject = models.ForeignKey(aclobject, on_delete=models.CASCADE)
	#users = models.ManyToManyField(profileuser, verbose_name='Пользователи', blank=True)
	user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')
	type = models.CharField(verbose_name='Права', max_length=80, choices=grantchoice, default='R')
	#
	ctime = models.DateTimeField(verbose_name='Время начало', blank=True, null=True)
	etime = models.DateTimeField(verbose_name='Время конец', blank=True, null=True)
	
	def __str__(self):
		return u'%s %s (%s-%s)' % (self.aclobject.name, self.user, self.type, self.get_type_display())

	class Meta:
		ordering=['-id']
		verbose_name = u'aclu'
		verbose_name_plural = u'aclu'		

		
class aclg(models.Model):
	id = models.AutoField(primary_key=True, unique=True, verbose_name='id')
	#name = models.CharField(verbose_name=u'Название', max_length=200)
	status = models.BooleanField(verbose_name='Статус', default=True)
	#
	aclobject = models.ForeignKey(aclobject, on_delete=models.CASCADE)
	group = models.ForeignKey(Group, on_delete=models.CASCADE, verbose_name='Группа')
	type = models.CharField(verbose_name='Права', max_length=80, choices=grantchoice, default='R')
	#
	ctime = models.DateTimeField(verbose_name='Время начало', blank=True, null=True)
	etime = models.DateTimeField(verbose_name='Время конец', blank=True, null=True)
	
	def __str__(self):
		return u'%s' % (self.id)

	class Meta:
		ordering=['-id']
		verbose_name = u'aclg'
		verbose_name_plural = u'aclg'	

shop/acl/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render_to_response
from django.shortcuts import HttpResponseRedirect
from django.template import RequestContext
from django.shortcuts import get_object_or_404
from django.http import Http404
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponsePermanentRedirect

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.views.decorators.csrf import csrf_exempt

from django.utils.safestring import mark_safe

from django.core.exceptions import PermissionDenied

from django import forms
from django.core.exceptions import ValidationError
from django.contrib import auth
from django.contrib.auth.models import User, Group

from django.urls import reverse

import json
from django.core import serializers

from django.http import QueryDict

from django.views.generic import DetailView, ListView, DeleteView
from django.views.generic.edit import CreateView, FormView, UpdateView
from django.views.generic.base import TemplateView

from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.utils.decorators import method_decorator

import datetime, time


from django.db.models import Max, Sum, Count
from django.db.models import Q, F

from ckeditor.widgets import CKEditorWidget

from django.core.mail import send_mail

from node.templatetags.nodetag import *

from dj.views import *
from node.models import *
from panel.models import *
from .models import *

import logging
log = logging.getLogger(__name__)



def get_object_or_denied(user, objectid, typeperm):
	################################
	##allow all for admin username
	if user.id == 1 or user.id == 2:
		return True
	################################
	##test for All grants
	aclutest=aclu.objects.filter(user=user, aclobject__objectid=objectid, status=True)
	if aclutest.filter(type='A'):
		pass
	else:
		aclutest=aclutest.filter(type=typeperm)
	#
	aclgtest=aclg.objects.filter(group__user=user, aclobject__objectid=objectid, status=True)
	if aclgtest.filter(type='A'):
		pass
	else:
		aclgtest=aclgtest.filter(type=typeperm)
	#
	if not aclutest.exists(): 
		if not aclgtest.exists():
			raise PermissionDenied
	return True




#@method_decorator(permission_required('node.add_goods'), name='dispatch')
class acl_perm_list(ListView):
	template_name = 'acl_perm_list.html'
	model = aclobject
	#paginate_by = 10
	
	def dispatch(self, request, *args, **kwargs):
		get_object_or_denied(self.request.user, 'acl', 'R') #проверяем права
		return super(acl_perm_list, self).dispatch(request, *args, **kwargs)
		
	def get_queryset(self):
		data=super(acl_perm_list, self).get_queryset()
		return data
		
	def get_context_data(self, *args, **kwargs):
		context_data = super(acl_perm_list, self).get_context_data(*args, **kwargs)
		#context_data.update({'req': self.req,})
		return context_data

		
#@method_decorator(permission_required('node.add_goods'), name='dispatch')
class acl_aclu_edit(UpdateView):
	model = aclu
	template_name = 'acl_perm_edit.html'
	success_url = '/acl/perm/list'
	fields = ['status', 'aclobject', 'user', 'type', 'ctime', 'etime',]
	#
	saveonclose = False #Кнопка Сохранить и закрыть
	
	
	def dispatch(self, request, *args, **kwargs):
		get_object_or_denied(self.request.user, 'acl', 'U') #проверяем права
		#self.e = get_object_or_404(self.model, id=self.kwargs['pk'], user=request.user) #ПОТОМ ВКЛЮЧИТЬ
		return super(acl_aclu_edit, self).dispatch(request, *args, **kwargs)
	
	def get_success_url(self):
		url = reverse('acl:acl_perm_list')
		return url
	
	def get_context_data(self, **kwargs):
		context = super(acl_aclu_edit, self).get_context_data(**kwargs)
		context['object'] = self.get_object()
		return context
	
	# def get_initial(self):
		# return {'buyer':self.b, 'user': self.request.user}
	
	# def get_form(self, form_class=None):
		# if form_class is None:
			# form_class = self.get_form_class()
			# form = super(acl_aclu_edit, self).get_form(form_class)
			# form.fields['saveonclose'].widget=forms.HiddenInput()
			# return form
		# return form_class(**self.get_form_kwargs())
	
	#def form_invalid(self, form):
		#print form.errors
	#	return super(acl_aclu_edit, self).form_invalid(form)
		
		
#@method_decorator(permission_required('node.add_eventcall'), name='dispatch')
class acl_aclu_add(CreateView):
	model = aclu
	template_name = 'acl_aclu_add.html'
	success_url = '/acl/perm/list'
	fields = ['status', 'aclobject', 'user', 'type', 'ctime', 'etime',]

	def dispatch(self, request, *args, **kwargs):
		get_object_or_denied(self.request.user, 'acl', 'C') #проверяем права
		self.data = get_object_or_404(aclobject, id=self.kwargs['pk'])
		return super(acl_aclu_add, self).dispatch(request, *args, **kwargs)
	
	#def get_success_url(self):
	#	return '%s/%s' % (self.success_url, self.hashkey)
	
	def get_context_data(self, **kwargs):
		context = super(acl_aclu_add, self).get_context_data(**kwargs)
		#context['object'] = self.data
		return context
	
	def get_initial(self):
		return {'aclobject':self.data,}
		
	# def get_form(self, form_class=None):
		# if form_class is None:
			# form_class = self.get_form_class()
			# form = super(acl_aclu_add, self).get_form(form_class)
			# form.fields['buyer'].widget=forms.HiddenInput()
			# #form.fields['buyer'].widget.attrs['readonly'] = True
			# #form.fields['user'].widget=forms.HiddenInput()
			# return form
		# return form_class(**self.get_form_kwargs())
	
	# def form_valid(self, form):
		# #self.object = form.save(commit=False)
		# #self.object.user = self.request.user
		# #self.object.save()
		# return super(acl_aclu_add, self).form_valid(form)
		
	#def form_invalid(self, form):
		#print form.errors
	#	return super(acl_aclu_add, self).form_invalid(form)

#@method_decorator(permission_required('panel.add_childbook'), name='dispatch')		
class acl_aclu_del(DeleteView):
	model = aclu
	template_name = '_confirm_delete.html'
	success_url = '/acl/perm/list'

	def dispatch(self, request, *args, **kwargs):
		get_object_or_denied(self.request.user, 'acl', 'U') #проверяем права
		self.data = get_object_or_404(self.model, id=self.kwargs['pk'])
		return super(acl_aclu_del, self).dispatch(request, *args, **kwargs)
	
	#def get_object(self, queryset=None):
	#	return get_object_or_404(self.model, id=self.kwargs['pk'])
		
	def get_context_data(self, **kwargs):
		context = super(acl_aclu_del, self).get_context_data(**kwargs)
		context['object'] = self.data.id
		context['msg'] = u'Вы уверены что хотите удалить '
		context['back_url'] = '/acl/perm/list'
		return context
		
		
##

#@method_decorator(permission_required('node.add_goods'), name='dispatch')
class acl_aclg_edit(UpdateView):
	model = aclg
	template_name = 'acl_perm_edit.html'
	success_url = '/acl/perm/list'
	fields = ['status', 'aclobject', 'group', 'type', 'ctime', 'etime',]
	#
	saveonclose = False #Кнопка Сохранить и закрыть
	
	def dispatch(self, request, *args, **kwargs):
		get_object_or_denied(self.request.user, 'acl', 'U') #проверяем права
		#self.e = get_object_or_404(self.model, id=self.kwargs['pk'], user=request.user) #ПОТОМ ВКЛЮЧИТЬ
		return super(acl_aclg_edit, self).dispatch(request, *args, **kwargs)
	
	def get_success_url(self):
		url = reverse('acl:acl_perm_list')
		return url
	
	def get_context_data(self, **kwargs):
		context = super(acl_aclg_edit, self).get_context_data(**kwargs)
		context['object'] = self.get_object()
		return context
		
		
#@method_decorator(permission_required('node.add_eventcall'), name='dispatch')
class acl_aclg_add(CreateView):
	model = aclg
	template_name = 'acl_aclg_add.html'
	success_url = '/acl/perm/list'
	fields = ['status', 'aclobject', 'group', 'type', 'ctime', 'etime',]

	def dispatch(self, request, *args, **kwargs):
		get_object_or_denied(self.request.user, 'acl', 'C') #проверяем права
		self.data = get_object_or_404(aclobject, id=self.kwargs['pk'])
		return super(acl_aclg_add, self).dispatch(request, *args, **kwargs)
	
	#def get_success_url(self):
	#	return '%s/%s' % (self.success_url, self.hashkey)
	
	def get_context_data(self, **kwargs):
		context = super(acl_aclg_add, self).get_context_data(**kwargs)
		#context['object'] = self.data
		return context
	
	def get_initial(self):
		return {'aclobject':self.data,}

#@method_decorator(permission_required('panel.add_childbook'), name='dispatch')		
class acl_aclg_del(DeleteView):
	model = aclg
	template_name = '_confirm_delete.html'
	success_url = '/acl/perm/list'

	def dispatch(self, request, *args, **kwargs):
		get_object_or_denied(self.request.user, 'acl', 'U') #проверяем права
		self.data = get_object_or_404(self.model, id=self.kwargs['pk'])
		return super(acl_aclg_del, self).dispatch(request, *args, **kwargs)

	def get_context_data(self, **kwargs):
		context = super(acl_aclg_del, self).get_context_data(**kwargs)
		context['object'] = self.data.id
		context['msg'] = u'Вы уверены что хотите удалить '
		context['back_url'] = '/acl/perm/list'
		return context
		

		
'''		
@method_decorator(permission_required('node.add_goods'), name='dispatch')
class goods_detail(DetailView):
	model = goods
	template_name = 'goods_detail.html'
	
	def dispatch(self, request, *args, **kwargs):
		self.data = get_object_or_404(self.model, id=self.kwargs['pk'])
		return super(goods_detail, self).dispatch(request, *args, **kwargs)
	
	def get_object(self, queryset=None):
		return self.data

	def get_context_data(self, **kwargs):
		context = super(goods_detail, self).get_context_data(**kwargs)
		#context['servername'] = self.data.name
		return context


		
class Form_goods_edit(forms.ModelForm):
	#saveonclose = forms.BooleanField(required=False, widget=forms.HiddenInput())
	saveonclose = forms.CharField(widget=forms.HiddenInput(), max_length=10, required=False)
	class Meta:
		model = goods

shop/acl/templates/acl_aclg_add.html
{% extends "base.html" %}
{% block title %}Панель управления{% endblock %}
{% block description %}Панель управления{% endblock %}
{% block keywords %}{% endblock %}


{% block content %}

{% load nodetag %}




<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<h3>Редактировать <small>{{ object.name }}</small></h3>
		</div>
	</div>
</div>

	
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">

			{% include "_form.html" %}
			
			
		</div>
	</div>
</div>
	
	
	
	</br>

{% endblock %}

shop/acl/templates/acl_aclu_add.html
{% extends "base.html" %}
{% block title %}Панель управления{% endblock %}
{% block description %}Панель управления{% endblock %}
{% block keywords %}{% endblock %}


{% block content %}

{% load nodetag %}




<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<h3>Редактировать <small>{{ object.name }}</small></h3>
		</div>
	</div>
</div>

	
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">

			{% include "_form.html" %}
			
			
		</div>
	</div>
</div>
	
	
	
	</br>

{% endblock %}

shop/acl/templates/acl_perm_edit.html
{% extends "base.html" %}
{% block title %}Панель управления{% endblock %}
{% block description %}Панель управления{% endblock %}
{% block keywords %}{% endblock %}


{% block content %}

{% load nodetag %}




<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<h3>Редактировать <small>{{ object.name }}</small></h3>
		</div>
	</div>
</div>

	
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">

			{% include "_form.html" %}
			
			
		</div>
	</div>
</div>
	
	
	
	</br>

{% endblock %}

shop/acl/templates/acl_perm_list.html
{% extends "base.html" %}
{% block title %}Панель управления{% endblock %}
{% block description %}Панель управления{% endblock %}
{% block keywords %}{% endblock %}


{% block content %}

{% load nodetag %}
{#{% load acltag %}#}




<!-- widget grid -->
<section id="widget-grid" class="">
	<!-- START ROW -->
	<div class="row">

		<!-- NEW COL START -->
		<article class="col-sm-12 col-md-12 col-lg-12">

			<!-- Widget ID (each widget will need unique ID)-->
			<div class="jarviswidget jarviswidget-color-darken" id="wid-id-0" data-widget-editbutton="false">
				<!-- widget options:
				usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">

				data-widget-colorbutton="false"
				data-widget-editbutton="false"
				data-widget-togglebutton="false"
				data-widget-deletebutton="false"
				data-widget-fullscreenbutton="false"
				data-widget-custombutton="false"
				data-widget-collapsed="true"
				data-widget-sortable="false"

				-->
				<header>
					<span class="widget-icon"> <i class="fa fa-table"></i> </span>
					<h2></h2>
				</header>

				<!-- widget div-->
				<div>

					<!-- widget edit box -->
					<div class="jarviswidget-editbox">
						<!-- This area used as dropdown edit box -->

					</div>
					<!-- end widget edit box -->

					<!-- widget content -->
					<div class="widget-body no-padding">
						<div class="table-responsive">
							<table class="table table-bordered table-striped">
								<thead>
									<tr>
										<th>id</th>
										<th>Название</th>
										<th>Пользователи</th>
										<th>Группы</th>
									</tr>
								</thead>
								<tbody>
									{% for i in object_list %}
									<tr>
										<td>{{ i.id }}</td>
										<td>
											{{ i.name }}</br>
											id: {{ i.objectid }}
										</td>
										<td>
											{% for u in i.aclu_set.all %}
												<b>{{ u.user.first_name }} {{ u.user.last_name }} ({{ u.user.username }})</b> {{ u.get_type_display }} ({{ u.type }}) ({{ u.status|yesno:"Включено,Выключено,Отст." }}) <a href="{% url 'acl:acl_aclu_edit' u.id %}">[...]</a> <a href="{% url 'acl:acl_aclu_del' u.id %}">[x]</a> </br>
											{% endfor %}
											<div class="form-group">
												<a href="{% url 'acl:acl_aclu_add' i.id %}" class="btn btn-success btn-block btn-xs">Добавить</a>
											</div>
										
										</td>
										<td>
											{% for g in i.aclg_set.all %}
												<b>{{ g.group.name }}</b> {{ g.get_type_display }} ({{ g.type }}) ({{ g.status|yesno:"Включено,Выключено,Отст." }}) <a href="{% url 'acl:acl_aclg_edit' g.id %}">[...]</a> <a href="{% url 'acl:acl_aclg_del' g.id %}">[x]</a></br>
												
												<ul>
												{% for u in g.group.user_set.all %}
													<li>{{ u.first_name }} {{ u.last_name }} ({{ u.username }})</li>
												{% endfor %}
												</ul>
												</br>
											{% endfor %}
											<div class="form-group">
												<a href="{% url 'acl:acl_aclg_add' i.id %}" class="btn btn-success btn-block btn-xs">Добавить</a>
											</div>
										</td>
									</tr>
									{% endfor %}
								</tbody>
							</table>
						</div>
					</div>
					<!-- end widget content -->

				</div>
				<!-- end widget div -->

			</div>
			<!-- end widget -->

		</article>
		<!-- END COL -->

	</div>

	<!-- END ROW -->
</section>

{% endblock %}